 zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero
gradient not equals to zero